export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_PENDING = 'GET_EMPLOYEES_PENDING';
export const GET_EMPLOYEES_ERROR = 'GET_EMPLOYEES_ERROR';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_PENDING = 'DELETE_EMPLOYEE_PENDING';
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_PENDING = 'ADD_EMPLOYEE_PENDING';
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_PENDING = 'EDIT_EMPLOYEE_PENDING';
export const EDIT_EMPLOYEE_ERROR = 'EDIT_EMPLOYEE_ERROR';
export const PUSH_PROJECTS_ASSOCIATED_IN_EMPLOYEE_SUCCESS =
  'PUSH_PROJECTS_ASSOCIATED_IN_EMPLOYEE_SUCCESS';
export const PUSH_PROJECTS_ASSOCIATED_IN_EMPLOYEE_PENDING =
  'PUSH_PROJECTS_ASSOCIATED_IN_EMPLOYEE_PENDING';
export const PUSH_PROJECTS_ASSOCIATED_IN_EMPLOYEE_ERROR =
  'PUSH_PROJECTS_ASSOCIATED_IN_EMPLOYEE_ERROR';
export const PUSH_EDIT_PROJECTS_ASSOCIATED_IN_EMPLOYEE_SUCCESS =
  'PUSH_EDIT_PROJECTS_ASSOCIATED_IN_EMPLOYEE_SUCCESS';
export const PUSH_EDIT_PROJECTS_ASSOCIATED_IN_EMPLOYEE_PENDING =
  'PUSH_EDIT_PROJECTS_ASSOCIATED_IN_EMPLOYEE_PENDING';
export const PUSH_EDIT_PROJECTS_ASSOCIATED_IN_EMPLOYEE_ERROR =
  'PUSH_EDIT_PROJECTS_ASSOCIATED_IN_EMPLOYEE_ERROR';
export const PULL_PROJECTS_ASSOCIATED_IN_EMPLOYEE_SUCCESS =
  'PULL_PROJECTS_ASSOCIATED_IN_EMPLOYEE_SUCCESS';
export const PULL_PROJECTS_ASSOCIATED_IN_EMPLOYEE_PENDING =
  'PULL_PROJECTS_ASSOCIATED_IN_EMPLOYEE_PENDING';
export const PULL_PROJECTS_ASSOCIATED_IN_EMPLOYEE_ERROR =
  'PULL_PROJECTS_ASSOCIATED_IN_EMPLOYEE_ERROR';
