export const GET_TASKS_FULLFILLED = 'GET_TASKS_FULLFILLED';
export const GET_TASKS_PENDING = 'GET_TASKS_PENDING';
export const GET_TASKS_FAILED = 'GET_TASKS_FAILED';

export const ADD_TASK_FULLFILLED = 'ADD_TASK_FULLFILLED';
// export const ADD_TASK_PENDING = 'ADD_TASK_PENDING';
// export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';

export const DELETE_TASK_FULLFILLED = 'DELETE_TASK_FULLFILLED';
// export const DELETE_TASK_PENDING = 'DELETE_TASK_PENDING';
// export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';

export const EDIT_TASK_FULLFILLED = 'EDIT_TASK_FULLFILLED';
// export const EDIT_TASK_PENDING = 'EDIT_TASK_PENDING';
// export const EDIT_TASK_FAILED = 'EDIT_TASK_FAILED';
