export const GET_TIMESHEET_FULFILLED = 'GET_TIMESHEET_FULFILLED';
export const GET_TIMESHEET_PENDING = 'GET_TIMESHEET_PENDING';
export const GET_TIMESHEET_FAILED = 'GET_TIMESHEET_FAILED';

export const ADD_TIMESHEET_FULFILLED = 'ADD_TIMESHEET_FULFILLED';
export const ADD_TIMESHEET_PENDING = 'ADD_TIMESHEET_PENDING';
export const ADD_TIMESHEET_FAILED = 'ADD_TIMESHEET_FAILED';

export const UPDATE_TIMESHEET_FULFILLED = 'UPDATE_TIMESHEET_FULFILLED';
export const UPDATE_TIMESHEET_PENDING = 'UPDATE_TIMESHEET_PENDING';
export const UPDATE_TIMESHEET_FAILED = 'UPDATE_TIMESHEET_FAILED';

export const DELETE_TIMESHEET_FULFILLED = 'DELETE_TIMESHEET_FULFILLED';
export const DELETE_TIMESHEET_PENDING = 'DELETE_TIMESHEET_PENDING';
export const DELETE_TIMESHEET_FAILED = 'DELETE_TIMESHEET_FAILED';

export const SHOW_CREATE_MODAL = 'SHOW_CREATE_MODAL';
export const SHOW_EDIT_MODAL = 'SHOW_EDIT_MODAL';
export const CLOSE_MODALS = 'CLOSE_MODALS';

export const GET_EMPLOYEE_TIMSHEET_FULFILLED = 'GET_EMPLOYEE_TIMSHEET_FULFILLED';
export const GET_EMPLOYEE_TIMSHEET_PENDING = 'GET_EMPLOYEE_TIMSHEET_PENDING';
export const GET_EMPLOYEE_TIMSHEET_FAILED = 'GET_EMPLOYEE_TIMSHEET_FAILED';

export const GET_TIMESHEETS_FROM_EMPLOYEE_FULFILLED = 'GET_TIMESHEETS_FROM_EMPLOYEE_FULFILLED';
export const GET_TIMESHEETS_FROM_EMPLOYEE_PENDING = 'GET_TIMESHEETS_FROM_EMPLOYEE_PENDING';
export const GET_TIMESHEETS_FROM_EMPLOYEE_FAILED = 'GET_TIMESHEETS_FROM_EMPLOYEE_FAILED';
