export const ADD_SUPERADMIN_SUCCESS = 'ADD_SUPERADMIN_SUCCESS';
export const ADD_SUPERADMIN_PENDING = 'ADD_SUPERADMIN_PENDING';
export const ADD_SUPERADMIN_ERROR = 'ADD_SUPERADMIN_ERROR';
export const EDIT_SUPERADMIN_SUCCESS = 'EDIT_SUPERADMIN_SUCCESS';
export const EDIT_SUPERADMIN_PENDING = 'EDIT_SUPERADMIN_PENDING';
export const EDIT_SUPERADMIN_ERROR = 'EDIT_SUPERADMIN_ERROR';