export const GET_PROJECTS_FULFILLED = 'GET_PROJECTS_FULFILLED';
export const GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING';
export const GET_PROJECTS_FAILED = 'GET_PROJECTS_FAILED';

export const ADD_NEW_PROJECT_FULFILLED = 'ADD_NEW_PROJECT_FULFILLED';
export const ADD_NEW_PROJECT_PENDING = 'ADD_NEW_PROJECT_PENDING';
export const ADD_NEW_PROJECT_FAILED = 'ADD_NEW_PROJECT_FAILED';

export const DELETE_PROJECT_FULFILLED = 'DELETE_PROJECT_FULFILLED';
export const DELETE_PROJECT_PENDING = 'DELETE_PROJECT_PENDING';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';

export const UPDATE_PROJECT_FULFILLED = 'UPDATE_PROJECT_FULFILLED';
export const UPDATE_PROJECT_PENDING = 'UPDATE_PROJECT_PENDING';
export const UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED';

export const CLOSE_ALL_MODALS = 'CLOSE_ALL_MODALS';
export const SHOW_CREATE_MODAL = 'SHOW_CREATE_MODAL';
export const SHOW_EDIT_MODAL = 'SHOW_EDIT_MODAL';

export const ADD_EMPLOYEE_TO_PROJECT = 'ADD_EMPLOYEE_TO_PROJECT';
export const ADD_EMPLOYEE_TO_PROJECT_PENDING = 'ADD_EMPLOYEE_TO_PROJECT';
export const ADD_EMPLOYEE_TO_PROJECT_FAILED = 'ADD_EMPLOYEE_TO_PROJECT';

export const ADD_TASK_TO_PROJECT = 'ADD_TASK_TO_PROJECT';
export const ADD_TASK_TO_PROJECT_PENDING = 'ADD_TASK_TO_PROJECT';
export const ADD_TASK_TO_PROJECT_FAILED = 'ADD_TASK_TO_PROJECT';
