export const GET_PROJECTS_FULFILLED = 'GET_PROJECTS_FULFILLED';
export const GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING';
export const GET_PROJECTS_FAILED = 'GET_PROJECTS_FAILED';

export const ADD_NEW_PROJECT_FULFILLED = 'ADD_NEW_PROJECT_FULFILLED';
export const ADD_NEW_PROJECT_PENDING = 'ADD_NEW_PROJECT_PENDING';
export const ADD_NEW_PROJECT_FAILED = 'ADD_NEW_PROJECT_FAILED';

export const DELETE_PROJECT_FULFILLED = 'DELETE_PROJECT_FULFILLED';
export const DELETE_PROJECT_PENDING = 'DELETE_PROJECT_PENDING';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';

export const UPDATE_PROJECT_FULFILLED = 'UPDATE_PROJECT_FULFILLED';
export const UPDATE_PROJECT_PENDING = 'UPDATE_PROJECT_PENDING';
export const UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED';
