export const GET_ADMINS_FULFILLED = 'GET_ADMINS_FULFILLED';
export const GET_ADMINS_PENDING = 'GET_ADMINS_PENDING';
export const GET_ADMINS_FAILED = 'GET_ADMINS_FAILED';

export const ADD_ADMIN_FULFILLED = 'ADD_ADMIN_FULFILLED';
export const ADD_ADMIN_PENDING = 'ADD_ADMIN_PENDING';
export const ADD_ADMIN_FAILED = 'ADD_ADMIN_FAILED';

export const UPDATE_ADMIN_FULFILLED = 'UPDATE_ADMIN_FULFILLED';
export const UPDATE_ADMIN_PENDING = 'UPDATE_ADMIN_PENDING';
export const UPDATE_ADMIN_FAILED = 'UPDATE_ADMIN_FAILED';

export const DELETE_ADMIN_FULFILLED = 'DELETE_ADMIN_FULFILLED';
export const DELETE_ADMIN_PENDING = 'DELETE_ADMIN_PENDING';
export const DELETE_ADMIN_FAILED = 'DELETE_ADMIN_FAILED';
