export const GET_CURRENT_USER_BY_EMAIL_SUCCESS = 'GET_CURRENT_USER_BY_EMAIL_SUCCESS';
export const GET_CURRENT_USER_BY_EMAIL_PENDING = 'GET_CURRENT_USER_BY_EMAIL_PENDING';
export const GET_CURRENT_USER_BY_EMAIL_ERROR = 'GET_CURRENT_USER_BY_EMAIL_ERROR';
export const SET_CURRENT_USER_TO_INITIAL_STATE = 'SET_CURRENT_USER_TO_INITIAL_STATE';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
